---
functional:
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
non-functional:
  - Корзина хранится в сессии браузера
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность очистить корзину после заказа
  - Пользователь должен иметь возможность добавлять товары в избранное
  - Пользователь должен иметь возможность зарегестрироваиться и войти на страницу сайта для оформления заказа
  - Пользователь должен иметь возможность выбрать пустое значение в фильтре-категорий товаров, которое отображает все товары вне зависимости от категории
